# Generated by Django 4.0.7 on 2022-11-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_created_at_post_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_added',)},
        ),
    ]
